### ISSUE TITLE
LoadVBX bug (not a SaveVBX  bug)

### ISSUE THREAD

**Issue by coreuml** [NVIDIA/gvdb-voxels#19]
In SaveVBX function,  at  line 1814
if (major >= 2) {
		fwrite( &use_bitmask, sizeof(uchar), 1, fp );		// bitmask usage (GVDB 2.0 or higher)
}

It 's not writed bitmask sign, but  in LoadVBX,  read this sign. 

Modified:
if ((major == 1 && minor >= 1) || major > 1) {
		fwrite( &use_bitmask, sizeof(uchar), 1, fp );		// bitmask usage (GVDB 2.0 or higher)
	}

**Comment by ramakarl** [comment]
Yes, that looks like a bug. 
The condition in LoadVBX is the correct one. If you make a pull request with SaveVBX fixed ti match it then i will merge.

**Comment by ramakarl** [comment]
Just to clarify whats going on here.
- In GVDB 1.0 the bitmask was required internally.
- In GVDB 1.1 the bitmask is not used. There is no option to use it.
- In GVDB 2.0+ it might be possible to use either, and this option would be saved to vbx files only in 2.0 and higher. 

The logic is:
If 1.0.then use_bitmask=true;
If 1.1 then use_bitmask=false;
If >2.0 then read/write use_bitmask to disk;

**Comment by NeilBickford-NV** [comment]
I've just pushed [commit c530d1aa](https://github.com/NVIDIA/gvdb-voxels/commit/c530d1aa0a501fc4c24e3c89be1da197957bd44c), which should fix this issue - it makes it so that if LoadVBX reads a version number of 2.0 or greater, then it loads `use_bitmask`, while if it reads a version number of 1.0, then it sets `use_bitmask` to true, and otherwise it sets `use_bitmask` to false. It also updates the VBX file specification to include these changes between different versions.
