### ISSUE TITLE
Missing CUDA_TOOLKIT_VERSION creates libcudpp_.so

### ISSUE THREAD

**Issue by markstock** [NVIDIA/gvdb-voxels#24]
I'm building CUDPP on CentOS 7 with CUDA installed in a non-standard location (but findable by cmake 3.9.6). My commands are:
```
cd gvdb-voxels
mkdir build_cudpp
cd build_cudpp
cmake -DCUDA_SDK_ROOT_DIR=/mnt/modules/cuda/cuda-9.0/samples -DCMAKE_BUILD_TYPE=Release ../source/shared_cudpp/
make
```
This builds the libs just fine, but the names of the .so files are wrong:
```
gvdb-voxels/build_cudpp $ ls -l lib/
total 35568
-rw-rw-r-- 1 mstock n-apps      559 Jun 12 10:19 cudpp-config.cmake
-rw-rw-r-- 1 mstock n-apps      396 Jun 12 10:19 cudpp-config.cmake.install
-rw-rw-r-- 1 mstock n-apps      295 Jun 12 10:19 cudpp-config-version.cmake
-rw-rw-r-- 1 mstock n-apps     2843 Jun 12 10:19 cudpp-targets.cmake
-rwxrwxr-x 1 mstock n-apps 35582064 Jun 12 10:22 libcudpp_.so
-rwxrwxr-x 1 mstock n-apps   815232 Jun 12 10:22 libcudpp_hash_.so
```
Naturally, this causes the gvdb cmake command to fail.
I can try to track down why cmake was able to find CUDA but didn't set CUDA_TOOLKIT_VERSION, but I think that `source/shared_cudpp/CMakeLists.txt` should throw an error if that variable is not defined.

**Comment by icoderaven** [comment]
You also get a similar issue if you're using CUDA 9.2

**Comment by NeilBickford-NV** [comment]
Hi markstock,

Just wanted to let you know that I'm closing this issue because we've since streamlined the build system (which now uses CMake's support for CUDA as a first-class language, which might fix this issue in addition to icoderaven's pull request). Please feel free to reopen this issue or to create a new issue if you're seeing any issues with it - thank you!
