### ISSUE TITLE
Texture sampling in compute shaders

### ISSUE THREAD

**Issue by meeree** [NVIDIA/gvdb-voxels#29]
Hi, I've been working with GVDB for a few months and I've been running into some weird behavior sampling from the atlas data. We're using an encoded UCHAR and a FLOAT channel to store the data for our compute kernels. However, we've run into issues trying to sample neighbors with the UCHAR where the samples are sometimes incorrect. 
Looking at the GVDB_COPY_SMEM_F macro I noticed that make_float3(0.5f,0.5f,0.5f) is added to the vox variable. However, with the other macros like GVDB_VOX and GVDB_COPY_SMEM_UC this is not added. I was wondering if there is a reason why (0.5f,0.5f,0.5f) is added before sampling in the GVDB_COPY_SMEM_F macro? Should this always be added when sampling the atlas, or only for floats, and why? It seems like adding (0.5,0.5,0.5) should perform interpolation on the sample, not giving us the exact value. 
Thanks.

**Comment by ramakarl** [comment]
The texture units are designed so that the sample values are located at the center of pixel or voxel cells. So the first non-interpolated sample is located at <0.5,0.5,0.5>. 

Interpolation is only performed on float textures since there is no way to return a fractional value from a uchar. Thus, only the float macros use the 0.5 offset to start at non-interp samples. The position <1,1,1> is actually interpolated 50% between the samples located at voxel centers.

-Rama

**Comment by meeree** [comment]
Okay that makes sense, thanks!
