### ISSUE TITLE
4D visulization

### ISSUE THREAD

**Issue by AndreFrelicot** [NVIDIA/gvdb-voxels#37]
Hello,
I'm evaluating the library to see if it fits my needs.
I just want to display medical volume data, say 512*512*512*sizeof(float) = 536MB of float data per frame. I need to display at least at 20fps.
The entire volume cannot fit inside the GPU.
Do you think I can copy fast enough the data from CPU to GPU ?

Can I use the concurrent copy engine (streams) with GVDB ?

Do you have advices on the best strategies ?

thank you

André

**Comment by ramakarl** [comment]
Hi André,

If there are only a few frames, you could fit them in CPU memory and then the PCI transfer should be fast enough.

To make it efficient, on the CPU you should first convert to the exact same format as it would exist in the GVBD channel. Do this as a preprocess by loading every frame into GVDB, then save every frame as a .VBX file with SaveVBX. Then just write a simple loop that calls LoadVBX for each file in sequence and renders it. This will ensure that each frame is stored efficiently since the .VBX format stores the raw atlas data.

On the other hand, if you really need better performance, then you could also pre-compress the data on the CPU side. Then you send over a compressed frame (low bandwidth) which is then uncompressed on-the-fly using Cuda and expands the atlas channel data directly into GPU memory. Currently .VBX does not support compression. This is more complex but would give better perf if implemented right.

Hope this help!,

Rama

**Comment by AndreFrelicot** [comment]
Hi Rama,
I my current testings  the LoadVBX function takes up to 74ms to complete. This is prohibitive for real time rendering.
I'll modify the LoadVBX to prevent file IO and read everything from CPU memory, this take ± 50%. The remaining time is taken by AtlasWriteSlice and UpdateAtlas.

I think I'll need to modify the GPU upload and use cuMemcpy3DAsync to upload the next frame while the current frame is being rendered. Do you think this is difficult to accomplish in the current GVDB architecture ? 
The next problem I'll face also is that I need 2 channels (density and velocity) ++ memory....


N.B:  I'm using GVDB 1.0 because I cannot get the 1.1 to work properly (see https://github.com/NVIDIA/gvdb-voxels/issues/34 )
I'll dig this problem later, if you have any clue it would be welcome.


Also, the file size of the VBX converted from my raw source (112 * 256 * 120 * sizeof(float) = (13,762,560) raw ) is 91MB.
Is this normal behavior ?


![image](https://user-images.githubusercontent.com/2123744/48630516-c0a59280-e9bc-11e8-8be7-61bd3b275b4b.png)

**Comment by AndreFrelicot** [comment]
more info, this time in dense mode, almost same size for the atlas

```
Activate GVDB volume.
  EXTENTS:
   Volume Res: 256 x 256 x 256
   Volume Max: 256 x 256 x 256
   Bound Min:  0.000000 x 0.000000 x 0.000000
   Bound Max:  256.000000 x 256.000000 x 256.000000
   Voxelsize:  1.000000 x 1.000000 x 1.000000
  VDB CONFIG: <3, 3, 3, 3, 4>:
             # Nodes / # Pool    Max Node  Ave Child  Max Child
   Level 0:     4096     4096       4096          0          0
   Level 1:        8        8          8        512        512
   Level 2:        1        1          2          8        512
   Level 3:        1        0          1          0          0
   Level 4:        1        0          1          0          0
   Ratio Interior/Total: 0.27%
  ATLAS STORAGE
   Atlas Res:     288 x 288 x 288  LeafCnt: 16 x 16 x 16  LeafDim: 16^3
   Vol Extents:   4096 bricks,  16.78 million voxels
   Atlas Storage: 4096 bricks,  16.78 million voxels
   Atlas Active:  4096 bricks,  16.78 million voxels
   Occupancy:     100.00%
  MEMORY USAGE:
   Topology Nodes:      0.25 MB (  0.25 MB active)
   Topology Bitmasks:   0.00 MB (  0.00 MB active)
   Topology Pointers:   0.05 MB (  0.04 MB active)
   Topology Total:      0.30 MB (  0.29 MB active)
   Atlas:
     Channel 0:        91.13 MB (4 bytes/vox)
   Atlas Total:        91.13 MB (Dense:      64.00 MB)
   Volume Total:       91.42 MB
Resample.
  Saving VBX (ver 1.0)
```

**Comment by ramakarl** [comment]
Hi Andre,

LoadVBX was designed to handle very large volumes, and potentially very sparse, so it works by loading the atlas in slice-at-a-time. That is, the entire volume may not be transferable with one dev-to-host copy, so it loads the atlas as slices. This is inefficient for smaller volumes that can be done with one copy. In addition, you have the overhead of loading in all the bricks. 

The right approach in your case is to have a LoadVBXFast which is able to handle smaller, possibly dense data. The first step is to replace the slices with one single copy. The second step is to handle the special case of dense data, where you don't need to load nodes at all because you know that *all* of them will be activated. Then you just call gvdb.ActivationRegion instead of loading each node from disk. 

Dont worry about using cuMemcpy3DAsync until you optimize all the other parts of the task. The main bottlenecks now are the slice transfers and loading nodes. Ideally, you'd like to transfer the entire, dense, 512^3 volume into a GVDB atlas with one single copy.

If your input data is 112 x 256 x 120 voxel, that is significantly smaller than 512^3. You may need to call gvdb.SetChannelDefaults (8, 8, 8), to configure the atlas structure to have smaller bricks.

Keep in mind that with such a small volume, you might be better off to simply use 3D textures alone, and bypass GVDB, since that small size can easily fit in one 3D texture. Then you just load the data from disk to your 3D texture on each frame. The primary use of GVDB is for very large volumes, but then you would also miss out on the rendering quality features (on-the-fly normals, transfer funcs, optix, etc.)

Rama
