### ISSUE TITLE
Voxel index restriction due to CUDPP Radix Sort

### ISSUE THREAD

**Issue by alvingitlord** [NVIDIA/gvdb-voxels#41]
https://github.com/NVIDIA/gvdb-voxels/blob/96781dd8becf7711bb4eeb50aed1d2b24203efb6/source/gvdb_library/kernels/cuda_gvdb_particles.cuh#L366-L368

The function argument for `gvdbCalcBrickId` requires the level-index list to be `unsigned short`, which I believe is due to the CUDPP radix sort limit of taking `CUDPP_LONGLONG`
https://github.com/NVIDIA/gvdb-voxels/blob/96781dd8becf7711bb4eeb50aed1d2b24203efb6/source/gvdb_library/src/gvdb_volume_gvdb.cpp#L2559-L2564
This limits the maximum voxel index to `0~2^(16+brick_log_res)`. Given `brick_log_res` is recommended to be `5`, the final limit is `0~2^21`, or `-2^20~2^20`. Could there be any other places that a tighter restriction exists?

**Comment by bigdimboom** [comment]
I'm glad that you brought this up. Have you found a solution to this?

**Comment by alvingitlord** [comment]
@bigdimboom No, I stopped worrying about this later on.

**Comment by NeilBickford-NV** [comment]
Hi alvingitlord and bigdimboom,

Just wanted to give you a heads-up that I'm closing this issue because version 1.1.1 removes CUDPP entirely (replacing its radix sort with Thrust's radix sort implementation)! Please feel free to reopen this issue or create a new issue if you wind up having any problems using it - thank you again!
