### ISSUE TITLE
Radius search in point cloud

### ISSUE THREAD

**Issue by lazysquid** [NVIDIA/gvdb-voxels#55]
Hello, I'm here for some helps.
Currently I'm implementing radius search(Specifically, I want to find a set of indices of registered point around the query point within the given radius.) for a given point using GVDB.
I'm implementing this because I expected that GVDB has this kind of function but I couldn't find any.
I've read quite some examples(particle surface, point cloud, point fusion) and guide documents but couldn't find the functionality that I want.

Am I missing somethings or GVDB does not have the kNN search function?

Thank you.

**Comment by alvingitlord** [comment]
Check this kernel function
https://github.com/NVIDIA/gvdb-voxels/blob/6f438f808ba9334acf2ee1122ca224c0988e7d25/source/gFluidSurface/fluid_system_cuda.cu#L247

**Comment by lazysquid** [comment]
@alvingitlord Thank you for your answer.
However, from my understanding, the kernel function doesn't fully utilize GVDB API.
The example could insert the cloud into GVDB.
Then for input queries we can find neighbor voxels of each quries and can do some NN searches items within the voxels.

Is there any specific reasons for implementation without GVDB features?

**Comment by ramakarl** [comment]
@lazysquid
Its not entirely clear what you want.
Is the "query point" another one of the registered points, is it an arbitrary point in space, or is it a voxel in gvdb?

If #1, this doesnt require gvdb at all, the link alvin gave in fluids v3 is correct. Since it is a point-to-point query no voxels are involved.

If #2, then the code for #1 should be used as a starting point. Uniforn subdiv is fastest.

If #3, the the code for #1 is also starting point. The query func would need to be placed into a gvdb voxel kernel.

The query func from #1 answers: "after points have been dropped into a uniform grid (not gdvb), what are all the bins which might need to be checked if i perform a query from a given bin up to a fixed radius. "

**Comment by lazysquid** [comment]
@ramakarl 
Thank you for your comments.

Yes. I'm looking for Fixed-radius-NN not kNN.

b) is the answer that I'm looking for.
More clearly,
1) I have millions of registered particles, the radius of each particles are zero.
And the number of registered particles will be increased as the time goes by.
(You can think point cloud stream from RGBD camera)
2) For arbitrary point `x` and search radius `r`, I want to find the indices of registered point around `x` within radius `r`.

What I wanted to do is similar to this but in my case, the input is arbitrary position x.
http://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf

Since the document of gvdb point said, gvdb insertion is utilizing the method above, so I was hoping I might use that internal feature without implementing it or implement the feature with relatively small amount of time and effort by using gvdb.
