### ISSUE TITLE
gInteractiveOptix and gInteractiveGL bounding boxes

### ISSUE THREAD

**Issue by ganterd** [NVIDIA/gvdb-voxels#56]
Managed to build gvdb, gInteractiveOptix and gInteractiveGL (albeit from https://github.com/icoderaven/gvdb-voxels/tree/feature/linux_build_fix, which doesn't look like it should effect any core code) and I'm seeing some issues with the bounding box structures during rendering. See the videos below for examples. 

With the Optix example, the bb for the volume seems to be way off the mark for some reason. With the GL example, there are chunks missing from the inside of the volume, and bb border planes seem to have random ray misses.

gInteractiveOptix: https://youtu.be/0ZqsJfMqT2I
gInteractiveGL: https://youtu.be/LCjhQ04YdE0

Any ideas what the issue here could be? I'll dig around to see if I can find the issue, but a starting guess point would be useful.

OS: Ubuntu 18.04.1LTS
GPU: RTX2080 
Driver: 418.30
Optix: 6.0.0
CUDA: 10.1

**Comment by ramakarl** [comment]
Glad you got it to build on your config.

Since these issues were not observed with earlier builds or sys configurations, I suggest rolling back each, one by one. 

It may help to start w earliest working config, eg. GTX 650 or 980, driver 316, optix 5.0.0 and cuda 9, to confirm it still works correctly with earliest known config. Then jump forward to your config and roll back each in order of gvdb merges, optix, driver, cuda, gpu, os, to isolate which layer introduced the change causing the issues.

**Comment by bigdimboom** [comment]
I'm visualizing an point cloud project using GVDB and I'm getting the similar issue.

The voxelization of a point cloud is correct because I can draw voxels in world space by querying "getNodeAtLevel". But it only renders 1/4 of volume after I call rendering using "gvdb.Render(...)".

**Comment by digbeta** [comment]
FYI, @NeilBickford-NV, I think this can be closed now that #89 has been fixed.
