### ISSUE TITLE
Generate project with OpenVDB

### ISSUE THREAD

**Issue by cjsb** [NVIDIA/gvdb-voxels#73]
I am trying to generate the project with cmake and I am getting this error: NOTE: OPENVDB is not enabled. Enable with the USE_OPENVDB option.

I am enabling the USE_OPENVDB and try to configure, the option gets disable automatically.

What can I do to solve it?

**Comment by NeilBickford-NV** [comment]
Hi cjsb,

Since this issue, we wound up rewriting the GVDB build system, so working with OpenVDB should be a bit easier (I think this issue was due to something in the old build system automatically turning USE_OPENVDB off as well, so I think your observation was right)! Please feel free to reopen this issue if you have problems building GVDB with OpenVDB now. Thanks!
