### ISSUE TITLE
error: class "VDBInfo" has no member "voxelsize"

### ISSUE THREAD

**Issue by NH89** [NVIDIA/gvdb-voxels#76]
Dear Rama, 
While compiling gFluidSurface I get the error 
sample_utils/optix_vol_intersect.cu(75): error: class "VDBInfo" has no member "voxelsize"

I noticed that your own fork differs in that, it does have 'voxelsize' in the definition of VDBInfo in cuda_gvdb.cuh .

It's 11pm in Australia now. I'll test your fork tomorrow.

Best regards,
Nick

**Comment by ramakarl** [comment]
Nick,

See the note pinned to issues on this topic. Voxelsize *should* be removed
from everywhere in GVDB library and samples, but not all samples have been
updated yet. Assume voxelsize=1 as per the pinned issue explanation.

This is likely because gFluidSurface sample is not yet updated to the
latest GVDB main lib. Just remove the SetVoxelSize call in that sample.

Rama

**Comment by NH89** [comment]
I have gFluidSample running now. I'll post a patch tomorrow.
Thanks,
Nick

**Comment by ramakarl** [comment]
Thanks! Patch merged /w main branch.
