### ISSUE TITLE
Linux compilation error 

### ISSUE THREAD

**Issue by MartinSamouiller** [NVIDIA/gvdb-voxels#8]
Hi, 
I have an error when I compile examples on my ubuntu computer (windows works fine),  the problem comes with the m_screenquad_utex. 

> main_x11.cpp:825:2: error: ‘m_screenquad_utex’ was not declared in this scope
>   m_screenquad_utex = glGetUniformLocation ( m_screenquad_prog, "uTex" );

And error in functions declaration : renderScreenQuadGL

> error: prototype for ‘void NVPWindow::renderScreenQuadGL(int, float, float, float, float, char, char)’ does not match any in class ‘NVPWindow’

Thanks,

**Comment by rchoetzlein** [comment]
Ah yes, there are minor changes to the sample utilities due to the two new github samples that have not yet been ported to linux. Changes in main_win.cpp to be migrated to main_linux.cpp. I will take a look at this asap.

**Comment by PabloCOVES** [comment]
@rchoetzlein Hi.
How it that going? Any hint on how to fix it by oursefl at the moment?
Thanks in advance!

**Comment by rchoetzlein** [comment]
Yeah, sorry I lost track of this.
You basically want to copy the missing code from main_win.cpp and put it into main_linux.cpp. This includes m_screenquad_utex (member var), renderScreenQuadGL (func), some glsl shaders (in-code strings), and possibly others. The linux side is out-of-date with respect to the new patterns present in main.h. Should be fairly easy fix since its entirely opengl code. A good approach might be to do a diff between main_win.cpp and main_linux.cpp. If you still have issues let me know.

**Comment by NeilBickford-NV** [comment]
Hi MartinSamouiller and PabloCOVES!

Just wanted to give you a heads-up that I'm closing this issue since it looks like the problem with the old build system has been fixed, and since 1.1.1 includes a new streamlined build system that fixes many of the problems with the old one. Please feel free to open a new issue or let me know if you have any problems building it. (Sorry for the ping on an old issue!)

Thanks!
