### ISSUE TITLE
AtlasRetrieveTexXYZ passes int argument to kernelRetrieveTexXYZ expecting int3.

### ISSUE THREAD

**Issue by digbeta** [NVIDIA/gvdb-voxels#82]
In the function _AtlasRetrieveTexXYZ_ in gvdb_allocator.cpp:769, cuLaunchKernel is called, passing _brickres_ (an int) to kernelRetrieveTexXYZ.   kernelRetrieveTexXYZ, however, expects an int3 value, resulting in invalid memory access errors.  The kernel uses texture references, which the docs indicate have been deprecated, but I wanted to note this in case it snags anyone else.

https://github.com/NVIDIA/gvdb-voxels/blob/c530d1aa0a501fc4c24e3c89be1da197957bd44c/source/gvdb_library/src/gvdb_allocator.cpp#L767-L776

https://github.com/NVIDIA/gvdb-voxels/blob/c530d1aa0a501fc4c24e3c89be1da197957bd44c/source/gvdb_library/kernels/cuda_gvdb_copydata.cu#L87-L92

**Comment by NeilBickford-NV** [comment]
Yep, this is a bug! I just pushed a change that should fix this by passing a Vector3DI instead of an int to this function and changing line 773. (It almost looks like the original author was trying to pass &mAtlas[chan].subdim.x, which would have worked, but the copy made it fail.) Thank you!

Unfortunately, I haven't been able to spot the use of texture references in this kernel yet - we've tried to remove them in 1.1.1, but please let me know when you spot any! - it looks like it's passing in a CUDA texture object, and then using template<class T>
T tex3D(cudaTextureObject_t texObj, float x, float y, float z) from [CUDA section B.8.1.8](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#tex3d-object), which seems OK so far?

**Comment by digbeta** [comment]
Cool, I'll check the fix this week.  Yes, you're correct, I am just learning about texture ref's vs. objects and was wrong about that.  Thanks for the quick fix!

**Comment by NeilBickford-NV** [comment]
Good to hear, thank you! I'll go ahead and close this issue, then.
