### ISSUE TITLE
Gaps in voxels:

### ISSUE THREAD

**Issue by bradrothenberg** [NVIDIA/gvdb-voxels#9]
Hi , I am wondering if this is only a bug on my hardware: GTX 1060m, win10 x64 -- I am getting gaps in the g3DPrint demo : 

![screenshot 5](https://user-images.githubusercontent.com/6138110/31299935-f5e7737a-aabe-11e7-91ba-c931b9daaf79.png)
![screenshot 6](https://user-images.githubusercontent.com/6138110/31299934-f5e61408-aabe-11e7-8250-ccf221dce49a.png)
![screenshot 7](https://user-images.githubusercontent.com/6138110/31299933-f5e44722-aabe-11e7-83e7-8c82a7af32b1.png)

**Comment by revillo** [comment]
Have you set your voxel size to be very low by any chance? (Like 0.001 units?) You might have some luck if you set a unit (1.0) voxel size and increase the size of your model proportionally. I think this may have to do with single precision / rounding limitations.

**Comment by rchoetzlein** [comment]
Confirm that UpdateApron is being called after the voxelization func.

**Comment by shincysl** [comment]
Same here. Just run the pre-compiled g3DPrint.exe. There are gaps at brick boundaries. UpdateApron is called and apron voxels are updated properly.

**Comment by shincysl** [comment]
Additionally, the last step in a brick does not terminates at the brick boundary. In most casts, the last point falls out of a brick. In the neighbor brick, gvdb should add the length from the last brick boundary to the last point. Because the transmittance is always computed using SCN_PSTEP. Actually, the first step in the next neighbor brick is smaller than one step if gvdb doesn't add it..

**Comment by shincysl** [comment]
One more thing. the alpha in gvdbRayDeep() is not correct.  If the ray hits nothing, the final alpha is 1.0

**Comment by rchoetzlein** [comment]
Check out the latest GVDB Voxels 1.1 release where this should be resolved.
